services:
  NetSpeedTestServer:
    image: python:3.12.9
    container_name: netSpeedTest
    restart: no
    entrypoint: "/bin/bash"
    command:
      - "-c"
      - "--"
      - "python /netSpeedTest/NetSpeedTest.py server 0.0.0.0 62345"
    volumes:
      - ./NetSpeedTest.py:/netSpeedTest/NetSpeedTest.py
    ports:
      - 62345:62345
    networks:
      - public

networks:
  public:
    external: true